[workspace]
authors = ["HuaTsai <huatsai42@gmail.com>"]
channels = ["conda-forge"]
name = "cuda-warmup"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
configure = "cmake -G Ninja -S . -B build"
build = { cmd = "cmake --build build", depends-on = ["configure"] }
test = { cmd = "ctest --test-dir build --output-on-failure", depends-on = ["build"] }

[system-requirements]
cuda = "12"

[dependencies]
cuda-toolkit = ">=12.9.2,<13"
gtest = ">=1.17.0,<2"
cmake = ">=4.2.3,<5"
ninja = ">=1.13.2,<2"
clang-tools = ">=21,<22"
clang = ">=21,<22"

